### PR TITLE
Redhat support

### PR DESCRIPTION
**Pull request by ricoli**
The good folks at DigiACTive have a fork that adds support for redhat, but it would be nice to have it as part of the original gem, so here it goes

### CODE REVIEW

**Comment by gael-ian** [comment]
As said in issue #18, I will add RedHat support as soon as somebody points me an *officially supported* repository for a bindfs package.

I can't find anyone and I'm not sure if the one provided by DigiACTive can be considered perennial or is just a quick fix for internal use only. Maybe someone at @DigiACTive can confirm? (Maybe @daxtens?)

**Comment by ricoli** [comment]
Sorry that I missed your comment on the issue - did a search on PRs for the topic but forgot to search on issues. Indeed it's a shame there's no package in official/supported repo. Pinging @ajdlinux too :)

**Comment by daxtens** [comment]
Yep, that's @ajdlinux's territory. DigiACTive itself is inactive, so the question would be if @ajdlinux wanted to keep supporting it.

**Comment by ajdlinux** [comment]
Unfortunately, I'm not in a position to continue supporting the package - as @daxtens noted, DigiACTive Pty Ltd has ceased operations and we no longer have a business need to maintain it.

It appears bindfs is still maintained in Fedora (https://apps.fedoraproject.org/packages/bindfs/), so I can't imagine it being too hard for someone who knows more about the Red Hat world than I to get it back into EPEL and maintained properly.

**Comment by gael-ian** [comment]
Thanks to you two.

The bindfs package for Fedora seems to be well maintained and may be a good start point. I've never used Red Hat but, as long as package format is the same, does yum allow to set up preferences on repos at a package level ? If so, we may be able to add the Fedora repository to any Red Hat (and derivatives) install and use it only for bindfs or does it sound silly to you ?

**Comment by ricoli** [comment]
Alas, I don't usually use Redhat distros (much prefer ubuntu), it's only a very recent need for a project - therefore I don't know much about RPMs. I'm thinking of maybe compiling from source, will give it a go.

**Comment by ricoli** [comment]
I did a quick and dirty compile from source, it seems to work fine... let me know your thoughts!

**Comment by ricoli** [comment]
also, I should probably redo this as a fork from original repo, the DigiACTive fork diverged a long time ago... shall I open up a new PR?

**Pull request closed without merging**
